services:
  - type: web
    name: buku_telepon
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn buku_telepon.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
