# Generated by Django 3.2.16 on 2022-11-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BukuTelepon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('no_telepon', models.CharField(max_length=13)),
                ('alamat', models.TextField()),
                ('perusahaan', models.CharField(max_length=255)),
            ],
        ),
    ]
